[package]
name = "rusty-tesseract"
version = "1.0.1"
edition = "2021"
authors = ["thomasgruebl"]
description = "A Rust wrapper for Google Tesseract"
license = "MIT"
repository = "https://github.com/thomasgruebl/rusty-tesseract"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subprocess = "0.2.8"
polars = "0.18.0"
ndarray = "0.15.4"
substring = "1.4.5"
multimap = "0.8.3"
image = "0.23.14"